apiVersion: v1
kind: Service
metadata:
  name: django-kubernetes
  labels:
    app: django-kubernetes
spec:
  type: LoadBalancer
  selector:
    app: django-kubernetes
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8181
